apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:8.6.3
          resources:
            limits:
              memory: "2Gi"
              cpu: "2000m"
            requests:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 6379
          command:
            - redis-server
            - /usr/local/etc/redis/redis.conf

          volumeMounts:
            - name: config
              mountPath: "/usr/local/etc/redis"

            - name: data
              mountPath: "/data"

      volumes:
        - name: config
          configMap:
            name: redis-config
            items:
              - key: redis.conf
                path: redis.conf

        - name: data
          persistentVolumeClaim:
            claimName: redis-pvc
