[gitea]
enabled = true
filter = gitea
logpath = /var/log/gitea.log
maxretry = 3
findtime = 5m
bantime = 4w

[postgres]
enabled= true
filter = postgres
logpath = /var/log/postgres.log
maxretry = 3
findtime = 5m
bantime = 4w