apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: domain-cert
  namespace: nginx-gateway
spec:
  secretName: tls-secret # shared-gateway中引用该secret名
  issuerRef:
    name: domain-cert-issuer
    kind: Issuer
  dnsNames:
    - "domain"
    - "wildcard.domain"
