apiVersion: v1
kind: ConfigMap
metadata:
  name: welcome-config
  namespace: welcome
data:
  nginx.conf: |
    server {
        listen 80;
        server_name domain;
        root /var/www/html;
        index index.html index.htm;
        location / {
            try_files $uri $uri/ =404;
        }
    }
