apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: welcome-pvc
  namespace: welcome
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
