apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-ssl
  namespace: pgadmin
type: Opaque
stringData:
  client.crt: |
    "-----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----"
  client.key: |
    "-----BEGIN PRIVATE KEY-----
    -----END PRIVATE KEY-----"
  ca.crt: |
    "-----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----"

---
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  namespace: pgadmin
type: Opaque
stringData:
  PGADMIN_DEFAULT_EMAIL: "email"
  PGADMIN_DEFAULT_PASSWORD: "password"
  PGADMIN_CONFIG_CONFIG_DATABASE_URI: "postgresql://user:password@host:5432/database"
