apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: postgres
type: Opaque
stringData: # 使用stringData，k8s会自动转换为base64
  postgres_user: xxx
  postgres_password: xxx
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-ssl
  namespace: postgres
type: Opaque
stringData:
  server.crt: |
    -----BEGIN CERTIFICATE-----

    -----END CERTIFICATE-----
  server.key: |
    -----BEGIN PRIVATE KEY-----

    -----END PRIVATE KEY-----
  ca.crt: |
    -----BEGIN CERTIFICATE-----

    -----END CERTIFICATE-----
