apiVersion: v1
kind: PersistentVolume
metadata:
  name: homer-pv
spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "slow"
  mountOptions:
    - hard
    - nfsvers=4.2
  nfs:
    path: /nfs/pv-homer
    server: 10.0.0.10
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homer-pvc
  namespace: homer
spec:
  resources:
    requests:
      storage: 50Mi
  storageClassName: "slow"
  accessModes:
    - ReadOnlyMany
  volumeName: homer-pv
