apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homer-pvc
  namespace: homer
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
