server {
    listen 80;
    listen [::]:80;
    server_name git.domain.eu.org;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;

    server_name git.domain.eu.org;

    ssl_certificate /etc/letsencrypt/domain.eu.org/fullchain.cer;
    ssl_certificate_key /etc/letsencrypt/domain.eu.org/domain.eu.org.key;

    client_max_body_size 0;

    location / {
        if ($http_origin ~* "^https?://(domain\.eu\.org|www\.domain\.eu\.org|dash\.domain\.eu\.org|dashboard\.domain\.eu\.org)$") {
            add_header 'Access-Control-Allow-Origin' '$http_origin';
        }
        proxy_set_header Connection $http_connection;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://gitea:3000;
    }
}