user nginx;
worker_processes auto;

events {
    worker_connections 4096;
}

http {
    server_tokens off;
    include mime.types;
    default_type application/octet-stream;

    gzip on;
    gzip_buffers 32 4k;
    gzip_comp_level 3;
    gzip_http_version 1.1;
    gzip_min_length 200;
    gzip_disable "MSIE [1-6]\.";
    gzip_static on;
    gzip_vary on;
    gzip_types text/plain text/css text/xml text/javascript image/svg+xml font/eot font/otf font/ttf font/woff font/woff2 application/atom+xml application/geo+json application/javascript application/x-javascript application/json application/ld+json application/manifest+json application/rdf+xml application/rss+xml application/xhtml+xml application/xml;

    gunzip on;
    gunzip_buffers 4 16k;

    keepalive_timeout 300s;
    send_timeout 300;

    proxy_headers_hash_max_size 51200;
    proxy_headers_hash_bucket_size 6400;

    real_ip_header X-Forwarded-For;
    set_real_ip_from 0.0.0.0/0;

    ## Set a variable to help us decide if we need to add the
    ## 'Docker-Distribution-Api-Version' header.
    ## The registry always sets this header.
    ## In the case of nginx performing auth, the header is unset
    ## since nginx is auth-ing before proxying.
    ## map $upstream_http_docker_distribution_api_version $docker_distribution_api_version {
    ##    '' 'registry/2.0';
    ## }

    include /etc/nginx/conf.d/*.conf;
    # upstream oyea {
    #    server servername;
    #    # server 192.168.1.2;
    #    # server 192.168.1.3;
    # }
}