apiVersion: v1
kind: Secret
metadata:
  name: hopin-secret
  namespace: hopin
type: Opaque
stringData:
  GITHUB_CLIENT_ID: xx
  GITHUB_CLIENT_SECRET: xx
  DATABASE_URL: postgresql://xx:xx@postgres-svc.postgres.svc.cluster.local:5432/hopin?sslmode=require
  DATA_ENCRYPTION_KEY: xx
---
apiVersion: v1
kind: Secret
metadata:
  name: hopin-ssl-cert
  namespace: hopin
type: Opaque
stringData:
  ca.crt: |
    ...
