apiVersion: v1
kind: ConfigMap
metadata:
  name: directus-config
  namespace: directus
data:
  DB_HOST: xxx
  DB_PORT: xxx
  DB_DATABASE: xxx
  CACHE_ENABLED: xxx
  CACHE_AUTO_PURGE: xxx
  CACHE_STORE: xxx
  PUBLIC_URL: xxx
