apiVersion: v1
kind: PersistentVolume
metadata:
  name: directus-uploads-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - hard
    - nfsvers=4.2
  nfs:
    path: /nfs/pv-directus/uploads
    server: 10.0.0.10
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: directus-extensions-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - hard
    - nfsvers=4.2
  nfs:
    path: /nfs/pv-directus/extensions
    server: 10.0.0.10
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: directus-uploads-pvc
  namespace: directus
spec:
  storageClassName: ""
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  volumeName: directus-uploads-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: directus-extensions-pvc
  namespace: directus
spec:
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  volumeName: directus-extensions-pv
