apiVersion: v1
kind: Secret
metadata:
  name: directus-secret
  namespace: directus
type: Opaque
stringData:
  SECRET: xxx
  DB_USER: xxx
  DB_PASSWORD: xxx
  REDIS_URL: xxx
  ADMIN_EMAIL: xxx
  ADMIN_PASSWORD: xxx
