# 第三步：gitea配置
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-config
  namespace: gitea
data:
  app.ini: |
    APP_NAME = 代码基地
    RUN_MODE = prod
    RUN_USER = git
    WORK_PATH = /data/gitea

    [repository]
    ROOT = /data/git/repositories
    DEFAULT_REPO_UNITS= ...

    [repository.local]
    LOCAL_COPY_PATH = /data/gitea/tmp/local-repo

    [repository.upload]
    TEMP_PATH = /data/gitea/uploads

    [server]
    APP_DATA_PATH = /data/gitea
    DOMAIN = git.oyee.eu.org
    SSH_DOMAIN = git.oyee.eu.org
    HTTP_PORT = 3000
    ROOT_URL = https://git.oyee.eu.org
    DISABLE_SSH = false
    SSH_PORT = 22
    SSH_LISTEN_PORT = 22
    LFS_START_SERVER = true
    LFS_JWT_SECRET = BlwlBldAQoJ34vykPB6EYkszwVwcVtK_ts3e-kIo1-Y
    OFFLINE_MODE = true

    [database]
    PATH = /data/gitea/gitea.db
    DB_TYPE = postgres
    HOST = postgres:5432
    NAME = gitea
    USER = supdbo
    PASSWD = 96e4e6d9d9c682e3de4c27161600d90c
    LOG_SQL = false
    SSL_MODE = verify-ca

    [indexer]
    ISSUE_INDEXER_PATH = /data/gitea/indexers/issues.bleve

    [session]
    PROVIDER_CONFIG = /data/gitea/sessions
    PROVIDER = file

    [picture]
    AVATAR_UPLOAD_PATH = /data/gitea/avatars
    REPOSITORY_AVATAR_UPLOAD_PATH = /data/gitea/repo-avatars

    [attachment]
    PATH = /data/gitea/attachments

    [log]
    ; MODE = console
    ; LEVEL = info
    ; ROOT_PATH = /data/gitea/log
    MODE = file
    LEVEL = info
    ROOT_PATH = /data/gitea/log
    logger.router.MODE = ,
    logger.access.MODE = access-file

    [log.access-file]
    MODE = file
    LEVEL = Info
    FILE_NAME = access.log

    ; [security]
    ; INSTALL_LOCK = false
    ; SECRET_KEY =
    ; REVERSE_PROXY_LIMIT = 1
    ; REVERSE_PROXY_TRUSTED_PROXIES = *
    [security]
    INSTALL_LOCK = true
    SECRET_KEY =
    REVERSE_PROXY_LIMIT = 1
    REVERSE_PROXY_TRUSTED_PROXIES = 127.0.0.1/8, 172.18.0.0/16
    INTERNAL_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE3Mzc1NTc5NTB9.kxDJ0vwkSjdJdIDw4oDRYHOwdDLYd0RjQ8EpaVDj6ik
    PASSWORD_HASH_ALGO = pbkdf2


    ; [service]
    ; DISABLE_REGISTRATION = false
    ; REQUIRE_SIGNIN_VIEW = false

    [service]
    DISABLE_REGISTRATION = true
    REQUIRE_SIGNIN_VIEW = true
    REGISTER_EMAIL_CONFIRM = false
    ENABLE_NOTIFY_MAIL = false
    ALLOW_ONLY_EXTERNAL_REGISTRATION = false
    ENABLE_CAPTCHA = true
    REQUIRE_CAPTCHA_FOR_LOGIN = true
    CAPTCHA_TYPE = cfturnstile
    CF_TURNSTILE_SECRET = 0x4AAAAAAA6CD0N47MdFR5Eeg_mYlG6IYow
    CF_TURNSTILE_SITEKEY = 0x4AAAAAAA6CD6v4Hq_F5MAK
    DEFAULT_KEEP_EMAIL_PRIVATE = true
    DEFAULT_ALLOW_CREATE_ORGANIZATION = false
    DEFAULT_ENABLE_TIMETRACKING = true
    NO_REPLY_ADDRESS = noreply.git.oyee.eu.org

    [lfs]
    PATH = /data/git/lfs

    [mailer]
    ENABLED = false

    [openid]
    ENABLE_OPENID_SIGNIN = false
    ENABLE_OPENID_SIGNUP = false

    [cron.update_checker]
    ENABLED = false

    [repository.pull-request]
    DEFAULT_MERGE_STYLE = merge

    [repository.signing]
    DEFAULT_TRUST_MODEL = committer

    [oauth2]
    JWT_SECRET = 3rfeiSTOJiPj0B9ekzhwXbmfS65SjANrTR1bhLtqPCE

    [actions]
    ENABLED = true
    ENDLESS_TASK_TIMEOUT = 24h
